"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kag(=6m+yhfh1o3y)n37qd#iskcz#_g5^2o_ipul7uv7f753a^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '192.168.0.27']
CURRENT_HOST = '127.0.0.1'
HOST_FULL_PATH = '127.0.0.1:8000'
#SUB_URL_EMPRESA = 'teamwork'
SUB_URL_EMPRESA = 'ntsoft'
SYSTEM_CODE = 'vcomida20'
NOMBRE_SISTEMA = 'PVI'

# base de datos
DATABASE_HOST = 'localhost'
DATABASE_USER = 'root'
DATABASE_PASSWORD = ''
DATABASE_NAME = 'comidav20'
# email contacto
EMAIL_CONTACT_FROM = 'contact@ntsoft-bolivia.com'
EMAIL_CONTACT_TO = 'acc.claros@gmail.com'
EMAIL_SERVER_NAME = 'ntsoft-bolivia.com'

# products configuration
PRODUCTOS_COSTOS = False
PRODUCTOS_PRECIOS_ABC = False

PRODUCTOS_USAR_FECHAS = False
PRODUCTOS_USAR_LOTE = False
PRODUCTOS_LBL_LOTE = 'talla'

# thumb imagen productos
PRODUCTOS_THUMB_WIDTH = 150
PRODUCTOS_THUMB_HEIGHT = 150


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'pages.apps.PagesConfig',
    'status.apps.StatusConfig',
    'configuraciones.apps.ConfiguracionesConfig',
    'permisos.apps.PermisosConfig',
    'clientes.apps.ClientesConfig',
    'cajas.apps.CajasConfig',
    'productos.apps.ProductosConfig',
    'inventarios.apps.InventariosConfig',
    'ventas.apps.VentasConfig',
    'webpush',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries':{
                'jinja_tags': 'templatetags.jinja_tags',
            }
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USER,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_HOST,
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# webpush
# https://web-push-codelab.glitch.me/
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BEUsLEzyTOOrgu9g533Hsof8Wy4dMnIyDjoONewh2eU5OweWfEe6Ee_dCIQDJLQH8xF60fYod_ghKUMd8EFW_4A",
    "VAPID_PRIVATE_KEY": "y2zqOr_amO-NZ2k1f4pYNndl68bgC64n1usfgrx8XEg",
    "VAPID_ADMIN_EMAIL": "acc.claros@gmail.com"
}

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'es-es'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'America/La_Paz'

USE_I18N = True

# formato de numeros
# USE_L10N = True
USE_L10N = False
DECIMAL_SEPARATOR = '.'

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# acc, para guardar las imagenes, en development y produccion (verificar)
STATIC_ROOT_APP = os.path.join(BASE_DIR, 'app', 'static')

# acc, ruta de archivos estaticos para tener varios sitios en el mismo host wsgi de apache
# se debe cambiar el alias de "/static/", caso contrario chocan entre los sitios web
# esta ruta esta definida en /etc/apache2/sites-available/000-default.conf
if CURRENT_HOST == '127.0.0.1':
    STATIC_URL = '/static/'
    SESSION_COOKIE_NAME = SYSTEM_CODE
else:
    STATIC_URL = '/' + SUB_URL_EMPRESA + '/' + 'static/'
    # nombre de los cookies por sitio web
    SESSION_COOKIE_NAME = SYSTEM_CODE

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'app/static')
]

# media folders settings
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Redirect to home URL after login (Default redirects to /accounts/profile/)
if CURRENT_HOST == '127.0.0.1':
    LOGIN_REDIRECT_URL = '/'
else:
    LOGIN_REDIRECT_URL = '/' + SUB_URL_EMPRESA

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

# proceso recpuerar contraseña email, link por consola porque no envia mails trabajando local
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# pedido de internet lugar id
LUGAR_PEDIDO_INTERNET = 1

# modulos
# ventas
MOD_VENTAS = 1
# clientes
MOD_CLIENTES = 2
# cajas
MOD_INICIAR_CAJA = 3
MOD_INICIAR_CAJA_RECIBIR = 4
MOD_ENTREGAR_CAJA = 5
MOD_ENTREGAR_CAJA_RECIBIR = 6
MOD_CAJAS_INGRESOS = 7
MOD_CAJAS_EGRESOS = 8
# users modulos
MOD_USUARIOS = 9
MOD_CIUDADES = 10
MOD_SUCURSALES = 11
MOD_PUNTOS = 12
MOD_CAJAS = 13
# configuraciones
MOD_CONFIGURACIONES_SISTEMA = 14
MOD_ALMACENES = 15
MOD_LINEAS = 16
# productos
MOD_PRODUCTOS = 17
MOD_INGRESOS_ALMACEN = 18
MOD_SALIDAS_ALMACEN = 19
MOD_MOVIMIENTOS_ALMACEN = 20
# tablas backup
MOD_TABLAS_BACKUP = 21
# reportes
MOD_REPORTES = 22
# cajas movimientos
MOD_CAJAS_MOVIMIENTOS = 23
MOD_ZONAS = 24
MOD_PROVEEDORES = 25
# pedidos de almacen
MOD_PEDIDOS_ALMACEN = 26
# preventas
MOD_PREVENTAS = 27
# plan pagos
MOD_PLAN_PAGOS = 28
# pedidos de los clientes
MOD_PEDIDOS = 29
# insumos y componentes
MOD_INSUMOS = 30
MOD_COMPONENTES = 31


# STATUS
STATUS_ACTIVO = 1
STATUS_INACTIVO = 2
STATUS_ELIMINADO = 3
STATUS_ANULADO = 4
# cajas
STATUS_APERTURA = 5
STATUS_APERTURA_RECIBE = 6
STATUS_CIERRE = 7
STATUS_CIERRE_RECIBE = 8
STATUS_NO_APERTURADO = 9
# MOVIMIENTO CAJA
STATUS_MOVIMIENTO_CAJA = 10
STATUS_MOVIMIENTO_CAJA_RECIBE = 11
# inventario
STATUS_INV_PEDIDO = 12
STATUS_INV_ENTREGA = 13
STATUS_INV_DEVOLUCION = 14
# ventas
STATUS_CONTADO = 15
STATUS_CONSIGNACION = 16
STATUS_PLAN_PAGO = 17
STATUS_CUOTA_PENDIENTE = 18
STATUS_CUOTA_PAGADA = 19
STATUS_FACTURA = 20
# preventas
STATUS_PREVENTA = 21
STATUS_PREVENTA_VENTA = 22

PERFIL_ADMIN = 1
PERFIL_SUPERVISOR = 2
PERFIL_CAJERO = 3

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
