# Generated by Django 3.2.7 on 2021-09-19 16:18

from django.db import migrations, models
import django.db.models.deletion
import utils.custome_db_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPagos',
            fields=[
                ('plan_pago_id', models.AutoField(db_column='plan_pago_id', primary_key=True, serialize=False)),
                ('registro_id', models.IntegerField(default=0)),
                ('venta_id', models.IntegerField(default=0)),
                ('preventa_id', models.IntegerField(default=0)),
                ('cliente_id', models.IntegerField(default=0)),
                ('punto_id', models.IntegerField(default=0)),
                ('fecha', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('concepto', models.CharField(max_length=250)),
                ('numero_cuotas', models.IntegerField(default=1)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cuota_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mensual_dias', models.CharField(max_length=20)),
                ('dia_mensual', models.IntegerField(default=1)),
                ('tiempo_dias', models.IntegerField(default=1)),
                ('user_perfil_id_anula', models.IntegerField(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'plan_pagos',
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('registro_id', models.AutoField(db_column='registro_id', primary_key=True, serialize=False)),
                ('almacen2_id', models.IntegerField(default=0)),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('numero_registro', models.IntegerField(default=0)),
                ('costo_abc', models.CharField(default='A', max_length=10)),
                ('fecha', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('fecha_salida_almacen', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('fecha_recibe_almacen', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('user_perfil_id_fecha', models.IntegerField(default=0)),
                ('user_perfil_id_salida_almacen', models.IntegerField(default=0)),
                ('user_perfil_id_recibe_almacen', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('concepto', models.CharField(max_length=250)),
                ('concepto_salida_almacen', models.CharField(max_length=250)),
                ('concepto_recibe_almacen', models.CharField(max_length=250)),
                ('user_perfil_id_anula', models.IntegerField(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('almacen_id', models.ForeignKey(db_column='almacen_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.almacenes')),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.puntos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'registros',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(db_column='stock_id', primary_key=True, serialize=False)),
                ('fecha_elaboracion', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('fecha_vencimiento', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('lote', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user_perfil_id_anula', models.IntegerField(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('almacen_id', models.ForeignKey(db_column='almacen_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.almacenes')),
                ('insumo_id', models.ForeignKey(db_column='insumo_id', on_delete=django.db.models.deletion.PROTECT, to='productos.insumos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='RegistrosDetalles',
            fields=[
                ('registro_detalle_id', models.AutoField(db_column='registro_detalle_id', primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_elaboracion', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('fecha_vencimiento', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('lote', models.CharField(max_length=50)),
                ('insumo_id', models.ForeignKey(db_column='insumo_id', on_delete=django.db.models.deletion.PROTECT, to='productos.insumos')),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.puntos')),
                ('registro_id', models.ForeignKey(db_column='registro_id', on_delete=django.db.models.deletion.PROTECT, to='inventarios.registros')),
            ],
            options={
                'db_table': 'registros_detalles',
            },
        ),
        migrations.CreateModel(
            name='PlanPagosPagos',
            fields=[
                ('plan_pago_pago_id', models.AutoField(db_column='plan_pago_pago_id', primary_key=True, serialize=False)),
                ('numero_cuota', models.IntegerField(default=1)),
                ('fecha', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user_perfil_id_paga', models.IntegerField(default=0)),
                ('cliente_id_paga', models.IntegerField(default=0)),
                ('persona_paga', models.CharField(max_length=250)),
                ('user_perfil_id_anula', models.IntegerField(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('plan_pago_id', models.ForeignKey(db_column='plan_pago_id', on_delete=django.db.models.deletion.PROTECT, to='inventarios.planpagos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'plan_pagos_pagos',
            },
        ),
        migrations.CreateModel(
            name='PlanPagosDetalles',
            fields=[
                ('plan_pago_detalle_id', models.AutoField(db_column='plan_pago_detalle_id', primary_key=True, serialize=False)),
                ('numero_cuota', models.IntegerField(default=1)),
                ('fecha', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user_perfil_id_anula', models.IntegerField(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('plan_pago_id', models.ForeignKey(db_column='plan_pago_id', on_delete=django.db.models.deletion.PROTECT, to='inventarios.planpagos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'plan_pagos_detalles',
            },
        ),
    ]
