# Generated by Django 3.2.7 on 2021-09-19 16:12

from django.db import migrations, models
import django.db.models.deletion
import utils.custome_db_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('componente_id', models.AutoField(db_column='componente_id', primary_key=True, serialize=False)),
                ('componente', models.CharField(default='', max_length=150)),
                ('codigo', models.CharField(default='', max_length=50)),
                ('imagen', models.CharField(default='', max_length=250, unique=True)),
                ('imagen_thumb', models.CharField(default='', max_length=250, unique=True)),
                ('posicion', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('es_aderezo', models.BooleanField(default=False)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'componentes',
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('insumo_id', models.AutoField(db_column='insumo_id', primary_key=True, serialize=False)),
                ('insumo', models.CharField(default='', max_length=150)),
                ('codigo', models.CharField(default='', max_length=50)),
                ('imagen', models.CharField(default='', max_length=250, unique=True)),
                ('imagen_thumb', models.CharField(default='', max_length=250, unique=True)),
                ('posicion', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'insumos',
            },
        ),
        migrations.CreateModel(
            name='PapasGrupo',
            fields=[
                ('papa_grupo_id', models.AutoField(db_column='papa_grupo_id', primary_key=True, serialize=False)),
                ('insumo_id', models.IntegerField(default=0)),
                ('componente_id', models.IntegerField(default=0)),
                ('posicion', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'papas_grupo',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('producto_id', models.AutoField(db_column='producto_id', primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=250, unique=True)),
                ('codigo', models.CharField(max_length=50)),
                ('codigo_barras', models.CharField(max_length=50)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('unidad', models.CharField(default='', max_length=20)),
                ('descripcion1', models.CharField(max_length=250)),
                ('descripcion2', models.CharField(max_length=250)),
                ('descripcion3', models.CharField(max_length=250)),
                ('descripcion4', models.CharField(max_length=250)),
                ('descripcion5', models.CharField(max_length=250)),
                ('descripcion6', models.CharField(max_length=250)),
                ('descripcion7', models.CharField(max_length=250)),
                ('descripcion8', models.CharField(max_length=250)),
                ('descripcion9', models.CharField(max_length=250)),
                ('descripcion10', models.CharField(max_length=250)),
                ('costo_a', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_b', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_c', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_a', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_b', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_c', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_a_factura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_b_factura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_c_factura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_a_consignacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_b_consignacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_c_consignacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_a_pp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_b_pp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_c_pp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user_id_anula', models.IntegerField(blank=True, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('linea_id', models.ForeignKey(db_column='linea_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.lineas')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='RefrescosGrupo',
            fields=[
                ('refresco_grupo_id', models.AutoField(db_column='refresco_grupo_id', primary_key=True, serialize=False)),
                ('insumo_id', models.IntegerField(default=0)),
                ('componente_id', models.IntegerField(default=0)),
                ('posicion', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'refrescos_grupo',
            },
        ),
        migrations.CreateModel(
            name='PuntosPrecios',
            fields=[
                ('producto_punto_precio_id', models.AutoField(db_column='producto_punto_precio_id', primary_key=True, serialize=False)),
                ('aumento_precio_a', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aumento_precio_b', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aumento_precio_c', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aumento_precio_a_factura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aumento_precio_b_factura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aumento_precio_c_factura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aumento_precio_a_consignacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aumento_precio_b_consignacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aumento_precio_c_consignacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aumento_precio_a_pp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aumento_precio_b_pp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aumento_precio_c_pp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.puntos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'puntos_precios',
            },
        ),
        migrations.CreateModel(
            name='ProductosRelacionados',
            fields=[
                ('producto_relacionado_id', models.AutoField(db_column='producto_relacionado_id', primary_key=True, serialize=False)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='primer_prodr', to='productos.productos', verbose_name='prod1r')),
                ('producto_relacion_id', models.ForeignKey(db_column='producto_relacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='segundo_prodr', to='productos.productos', verbose_name='prod2r')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'productos_relacionados',
            },
        ),
        migrations.CreateModel(
            name='ProductosRefrescos',
            fields=[
                ('producto_refresco_id', models.AutoField(db_column='producto_refresco_id', primary_key=True, serialize=False)),
                ('insumo_id', models.IntegerField(default=0)),
                ('componente_id', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('posicion', models.IntegerField(default=1)),
                ('defecto', models.BooleanField(default=False)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'productos_refrescos',
            },
        ),
        migrations.CreateModel(
            name='ProductosPapas',
            fields=[
                ('producto_papa_id', models.AutoField(db_column='producto_papa_id', primary_key=True, serialize=False)),
                ('insumo_id', models.IntegerField(default=0)),
                ('componente_id', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('posicion', models.IntegerField(default=1)),
                ('defecto', models.BooleanField(default=False)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'productos_papas',
            },
        ),
        migrations.CreateModel(
            name='ProductosInsumos',
            fields=[
                ('producto_insumo_id', models.AutoField(db_column='producto_insumo_id', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('insumo_id', models.ForeignKey(db_column='insumo_id', on_delete=django.db.models.deletion.PROTECT, to='productos.insumos')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'productos_insumos',
            },
        ),
        migrations.CreateModel(
            name='ProductosImagenes',
            fields=[
                ('producto_imagen_id', models.AutoField(db_column='producto_imagen_id', primary_key=True, serialize=False)),
                ('imagen', models.CharField(default='', max_length=250, unique=True)),
                ('imagen_thumb', models.CharField(default='', max_length=250, unique=True)),
                ('posicion', models.IntegerField(default=1)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'productos_imagenes',
            },
        ),
        migrations.CreateModel(
            name='ProductosExtras',
            fields=[
                ('producto_extra_id', models.AutoField(db_column='producto_extra_id', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('posicion', models.IntegerField(default=1)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('componente_id', models.ForeignKey(db_column='componente_id', on_delete=django.db.models.deletion.PROTECT, to='productos.componentes')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'productos_extras',
            },
        ),
        migrations.CreateModel(
            name='ProductosComponentes',
            fields=[
                ('producto_componente_id', models.AutoField(db_column='producto_componente_id', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('posicion', models.IntegerField(default=1)),
                ('defecto', models.BooleanField(default=False)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('componente_id', models.ForeignKey(db_column='componente_id', on_delete=django.db.models.deletion.PROTECT, to='productos.componentes')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'productos_componentes',
            },
        ),
    ]
