# Generated by Django 3.1.1 on 2020-09-07 19:57

from django.db import migrations
from status.models import Status


def load_data(apps, schema_editor):
    status_add = Status.objects.create(status_id=1, status='activo')
    status_add.save()
    status_add = Status.objects.create(status_id=2, status='inactivo')
    status_add.save()
    status_add = Status.objects.create(status_id=3, status='eliminado')
    status_add.save()
    status_add = Status.objects.create(status_id=4, status='anulado')
    status_add.save()
    # cajas
    status_add = Status.objects.create(status_id=5, status='apertura')
    status_add.save()
    status_add = Status.objects.create(status_id=6, status='apertura_recibe')
    status_add.save()
    status_add = Status.objects.create(status_id=7, status='cierre')
    status_add.save()
    status_add = Status.objects.create(status_id=8, status='cierre_recibe')
    status_add.save()
    status_add = Status.objects.create(status_id=9, status='no_aperturado')
    status_add.save()
    # movimientos de caja
    status_add = Status.objects.create(status_id=10, status='movimiento_caja')
    status_add.save()
    status_add = Status.objects.create(status_id=11, status='movimiento_caja_recibe')
    status_add.save()
    # inventario
    status_add = Status.objects.create(status_id=12, status='inventario_pedido')
    status_add.save()
    status_add = Status.objects.create(status_id=13, status='inventario_entrega')
    status_add.save()
    status_add = Status.objects.create(status_id=14, status='inventario_devolucion')
    status_add.save()
    # ventas
    status_add = Status.objects.create(status_id=15, status='venta_contado')
    status_add.save()
    status_add = Status.objects.create(status_id=16, status='venta_consignacion')
    status_add.save()
    status_add = Status.objects.create(status_id=17, status='venta_plan_pago')
    status_add.save()
    status_add = Status.objects.create(status_id=18, status='cuota_pendiente')
    status_add.save()
    status_add = Status.objects.create(status_id=19, status='cuota_pagada')
    status_add.save()
    status_add = Status.objects.create(status_id=20, status='factura')
    status_add.save()
    # preventas
    status_add = Status.objects.create(status_id=21, status='preventa')
    status_add.save()
    status_add = Status.objects.create(status_id=22, status='preventa_venta')
    status_add.save()


def delete_data(apps, schema_editor):
    status = apps.get_model('status', 'Status')
    status.objects.all().delete


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, delete_data),
    ]
