# Generated by Django 3.0.8 on 2020-07-18 21:31

from django.db import migrations
from django.contrib.auth.models import User

from permisos.models import Perfiles, UsersPerfiles, Modulos, UsersModulos
from status.models import Status


def load_data(apps, schema_editor):
    # perfiles
    perfil = Perfiles.objects.create(perfil_id=1, perfil='Administrador')
    perfil.save()
    perfil = Perfiles.objects.create(perfil_id=2, perfil='Supervisor')
    perfil.save()
    perfil = Perfiles.objects.create(perfil_id=3, perfil='Cajas')
    perfil.save()

    # users perfiles
    perfil1 = Perfiles.objects.get(pk=1)
    user2 = User.objects.get(pk=1)
    status_activo = Status.objects.get(pk=1)
    user_perfil = UsersPerfiles.objects.create(perfil_id=perfil1, user_id=user2, punto_id=1, caja_id=1, notificacion=1, status_id=status_activo, created_at='now', updated_at='now')
    user_perfil.save()

    # modulos
    # grupo 1, ventas
    modulo_insert = Modulos.objects.create(modulo_id=1, modulo='ventas', modulo_txt='Ventas', enabled=True, position=3, grupo=1)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=2, modulo='clientes', modulo_txt='Clientes', enabled=True, position=2, grupo=1)
    modulo_insert.save()

    # grupo2, operaciones caja
    modulo_insert = Modulos.objects.create(modulo_id=3, modulo='iniciar_caja', modulo_txt='Inicar Caja', enabled=True, position=9, grupo=2)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=4, modulo='iniciar_caja_recibir', modulo_txt='Aceptar Inicio Caja', enabled=True, position=10, grupo=2)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=5, modulo='entregar_caja', modulo_txt='Entregar Caja', enabled=True, position=11, grupo=2)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=6, modulo='entregar_caja_recibir', modulo_txt='Aceptar Entrega Caja', enabled=True, position=12, grupo=2)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=7, modulo='cajas_ingresos', modulo_txt='Ingresos Caja', enabled=True, position=13, grupo=2)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=8, modulo='cajas_egresos', modulo_txt='Egresos Caja', enabled=True, position=14, grupo=2)
    modulo_insert.save()

    # grupo 3, configuraciones
    modulo_insert = Modulos.objects.create(modulo_id=9, modulo='usuarios', modulo_txt='Usuarios', enabled=True, position=16, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=10, modulo='ciudades', modulo_txt='Ciudades', enabled=False, position=100, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=11, modulo='Sucursales', modulo_txt='Sucursales', enabled=True, position=19, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=12, modulo='puntos', modulo_txt='Puntos', enabled=True, position=18, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=13, modulo='cajas', modulo_txt='Cajas', enabled=False, position=100, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=14, modulo='configuraciones_sistema', modulo_txt='Configuraciones Sistema', enabled=True, position=21, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=15, modulo='almacenes', modulo_txt='Almacenes', enabled=False, position=100, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=16, modulo='lineas', modulo_txt='Lineas', enabled=True, position=17, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=17, modulo='productos', modulo_txt='Productos', enabled=True, position=1, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=18, modulo='ingresos_almacen', modulo_txt='Ingresos Almacen', enabled=True, position=5, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=19, modulo='salidas_almacen', modulo_txt='Salidas Almacen', enabled=True, position=6, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=20, modulo='movimientos_almacen', modulo_txt='Movimientos Almacen', enabled=True, position=7, grupo=3)
    modulo_insert.save()

    # grupo 4, herramientas
    modulo_insert = Modulos.objects.create(modulo_id=21, modulo='tablas_backup', modulo_txt='Backup', enabled=False, position=100, grupo=4)
    modulo_insert.save()

    # grupo 5, reportes
    modulo_insert = Modulos.objects.create(modulo_id=22, modulo='reportes', modulo_txt='Reportes', enabled=True, position=22, grupo=5)
    modulo_insert.save()

    # grup 2, cajas
    modulo_insert = Modulos.objects.create(modulo_id=23, modulo='cajas_movimientos', modulo_txt='Cajas Movimientos', enabled=True, position=15, grupo=2)
    modulo_insert.save()

    # grupo 1, zonas
    modulo_insert = Modulos.objects.create(modulo_id=24, modulo='zonas', modulo_txt='Zonas', enabled=True, position=19, grupo=1)
    modulo_insert.save()
    # grupo 1, proveedores
    modulo_insert = Modulos.objects.create(modulo_id=25, modulo='proveedores', modulo_txt='Proveedores', enabled=True, position=20, grupo=1)
    modulo_insert.save()
    # grupo 1, pedidos almacen
    modulo_insert = Modulos.objects.create(modulo_id=26, modulo='pedidos_almacen', modulo_txt='Pedidos Almacen', enabled=True, position=8, grupo=1)
    modulo_insert.save()
    # grupo 1, preventa
    modulo_insert = Modulos.objects.create(modulo_id=27, modulo='preventas', modulo_txt='PreVentas', enabled=True, position=4, grupo=1)
    modulo_insert.save()
    # grupo 1, plan pagos
    modulo_insert = Modulos.objects.create(modulo_id=28, modulo='plan_pagos', modulo_txt='Plan Pagos', enabled=True, position=1, grupo=1)
    modulo_insert.save()
    # grupo 1, pedidos clientes
    modulo_insert = Modulos.objects.create(modulo_id=29, modulo='pedidos', modulo_txt='Pedidos Clientes', enabled=True, position=1, grupo=1)
    modulo_insert.save()
    # insumos
    modulo_insert = Modulos.objects.create(modulo_id=30, modulo='insumos', modulo_txt='Insumos', enabled=True, position=1, grupo=1)
    modulo_insert.save()
    # componentes
    modulo_insert = Modulos.objects.create(modulo_id=31, modulo='componentes', modulo_txt='Componentes', enabled=True, position=1, grupo=1)
    modulo_insert.save()

    # para el usuarios por defecto
    modulo1 = Modulos.objects.get(pk=1)
    modulo2 = Modulos.objects.get(pk=2)
    modulo3 = Modulos.objects.get(pk=3)
    modulo4 = Modulos.objects.get(pk=4)
    modulo5 = Modulos.objects.get(pk=5)
    modulo6 = Modulos.objects.get(pk=6)
    modulo7 = Modulos.objects.get(pk=7)
    modulo8 = Modulos.objects.get(pk=8)
    modulo9 = Modulos.objects.get(pk=9)
    modulo10 = Modulos.objects.get(pk=10)
    modulo11 = Modulos.objects.get(pk=11)
    modulo12 = Modulos.objects.get(pk=12)
    modulo13 = Modulos.objects.get(pk=13)
    modulo14 = Modulos.objects.get(pk=14)
    modulo15 = Modulos.objects.get(pk=15)
    modulo16 = Modulos.objects.get(pk=16)
    modulo17 = Modulos.objects.get(pk=17)
    modulo18 = Modulos.objects.get(pk=18)
    modulo19 = Modulos.objects.get(pk=19)
    modulo20 = Modulos.objects.get(pk=20)
    modulo21 = Modulos.objects.get(pk=21)
    modulo22 = Modulos.objects.get(pk=22)
    modulo23 = Modulos.objects.get(pk=23)
    modulo24 = Modulos.objects.get(pk=24)
    modulo25 = Modulos.objects.get(pk=25)
    modulo26 = Modulos.objects.get(pk=26)
    modulo27 = Modulos.objects.get(pk=27)
    modulo28 = Modulos.objects.get(pk=28)
    modulo29 = Modulos.objects.get(pk=29)

    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo1, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo2, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo3, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo4, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo5, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo6, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo7, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo8, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo9, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo10, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo11, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo12, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo13, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo14, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo15, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo16, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo17, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo18, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo19, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo20, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo21, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo22, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo23, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo24, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo25, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo26, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo27, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo28, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_perfil_id=user_perfil, modulo_id=modulo29, enabled=True, adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()


def delete_data(apps, schema_editor):
    user_modulo = apps.get_model('permisos', 'UsersModulos')
    user_modulo.objects.all().delete

    modulo = apps.get_model('permisos', 'Modulos')
    modulo.objects.all().delete

    user_perfil = apps.get_model('permisos', 'UsersPerfiles')
    user_perfil.objects.all().delete

    perfil = apps.get_model('permisos', 'Perfiles')
    perfil.objects.all().delete


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, delete_data),
    ]
